### PR TITLE
Staging -> master: Use cookie session for auth

### PR DESCRIPTION
**Pull request by razzius**
Sql diff: 
```
alter table verification_token rename expired to logged_out;
alter table verification_token add column id serial not null;
alter table verification_token drop constraint verification_token_pkey;
alter table verification_token add primary key (id);
```

### CODE REVIEW

**Comment by razzius** [comment]
Noticed this warning in the console: 

Cookie “session” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by jjchen20** [comment]
What does this mean in terms of any action we need to take to ensure users
don't lose access?

**Comment by razzius** [comment]
This is a new feature, so it won't affect any users yet; before rolling it out, I'll need to set "secure" and "sameSite" properly.

**Comment by razzius** [comment]
@Chronowork1 I'm going to deploy staging without the is_faculty feature, so I force pushed to remove your commit from this branch. You can continue your work by pushing to your own `mentor-to-faculty` branch.

**Comment by Chronowork1** [comment]
Hey there Razzi, I guess I'm a bit confused at the moment, do you want me
to start over and create a new pull request for mentor-to-faculty and merge
the branches?

**Comment by razzius** [comment]
Update your mentor-to-faculty branch to be based on `master` now that staging is merged into master, then when tests pass, make a new pull request into `staging`.

**Comment by razzius** [comment]
@Chronowork1 you can reuse your old pull request, actually, and just change the base from `master` to `staging`.

To update your branch to be based on master, from your branch, you may find `git rebase` to be useful; if that isn't working, just make a new branch off of `master` and `git cherry-pick` each commit you want from your old branch.

**Comment by Chronowork1** [comment]
Alright, just to 100% clear and don't want to make any mistakes, so I'm
pushing the changes I made in the staging branch on a pull request and
merging it with the master branch.

This is optional: but I can also use git rebase or git cherry-pick to
combine my branches from *faculty-to-mentor *branch to *staging *branch and
merge it with master branch.

**Pull request merged**
